# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John Yong
email: johnyong@live.cn
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website and blogs on Github.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yikkok-yong.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  yikkok-yong
show_excerpts: true

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

livereload: true
reload_port: 5678

# Personal Variables
skills_title:
 - 'Programming Langauge'
 - 'Markup Langauge'
 - 'Applications'
 - 'OS'
 - 'Framework'
 - 'Others'
my_skills:
  - 'Programming Langauge': 'PHP, Android, Javascript, ECMAScript'
  - 'Markup Langauge': 'HTML5'
  - 'Applications': 'Visual Studio Code, Git, Trello'
  - 'OS': 'Windows, Linux (Ubuntu)'
  - 'Framework': 'Angular, Truffle, Bootstrap 3 and 4, React Native'
  - 'Others': 'NPM/Yarn'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
